BUS_INFO table;
 BUS_ID, NAME, NUMBER, SERVICE_START_DATE, SERVICE_END_DATE, CREATED_DATE, CREATED_BY, IS_DEACTIVATED.  

DAILY_BUS_ROUTINE TABLE;
 ID, BUS_ID, ROUTE_FROM, ROUTE_TO, TRAVEL_DATE, START_TIME, END_TIME, DRIVER_1, DRIVER_2, CLEANER, CREATED_DATE, IS_DEACTIVATED.

PASSENGER_BOOKING TABLE:
 ID, BUS_ID, SEAT_NO, NAME, ID_NUMBER, IS_PARENT, CONTACT, TRAVEL_FROM, TRAVEL_TO, TICKET_PRICE, TRAVEL_DATE, 
 CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, PICKUP_POINT, DROP_POINT, BOOKING_STATUS, IS_TRAVELLED, IS_DEACTIVATED
 	 NOTE: IS_PARENT will be used in case family is travelling then we just need family head person Id number.
 	 
BUS_POINTS TABLE;
ID, BUS_ID, PICKUP_POINT(places_id), DROP_POINT(places_id), IS_DEACTIVATED.

LOCATION TABLE;
ID, NAME, CITY_ID, IS_DEACTIVATED.

 