EMPLOYEE table:
ID, NAME, DOB, ID_NUMBER, ID_TYPE, EMP_TYPE, JOINING_DATE, LAST_WORKING_DATE, ADDRESS, CONTACT, SALARY, 
CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, IS_DEACTIVED.

EMP_TYPE TABLE;
ID,NAME,CREATED_DATE,IS_DEACTIVATED.  
	e.g DRIVER, CLEANER, MANAGER, AGENCY, ADMIN

ID_TYPE TABLE;
ID,NAME,CREATED_DATE,IS_DEACTIVATED.
	e.g: AADHAR, DRIVING, PAN

EMPLOYEE_LEAVES
ID, EMPLOYEE_ID, LEAVE_DATE, LEAVE_STATUS, LEAVE_DETAIL, APPROVED_BY, APPROVED_DATE, LEAVE_APPLY_DATE, IS_DEACTIVATED



